<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DLSSVersionToolkit.Core\DLSSVersionToolkit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>DLSSVersionToolkit</AssemblyName>
  <AssemblyVersion>0.0.20.0</AssemblyVersion>
  <FileVersion>0.0.20.0</FileVersion>
  <Version>0.0.20</Version>
    <Authors>scubamount</Authors>
    <Product>DLSS Version Toolkit</Product>
    <Description>WPF GUI for checking and upgrading NVIDIA DLSS versions</Description>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

</Project>
